#!/bin/bash

WORKDIR=$(pwd)
ln -s $WORKDIR $GOPATH/src/standardized
cd $GOPATH/src/standardized

curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
dep ensure

env GOOS=linux GOARCH=arm go build -v .
mv standardized standardized-linux-arm

env GOOS=linux GOARCH=arm64 go build -v .
mv standardized standardized-linux-arm64

env GOOS=linux GOARCH=amd64 go build -v .
mv standardized standardized-linux-amd64

env GOOS=linux GOARCH=386 go build -v .
mv standardized standardized-linux-x86

env GOOS=darwin GOARCH=amd64 go build -v .
mv standardized standardized-darwin-amd64
