#!/bin/bash

WORKDIR=$(pwd)
ln -s $WORKDIR $GOPATH/src/standardized
cd $GOPATH/src/standardized

curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
dep ensure
go install
cp  $GOPATH/bin/standardized standardized-$(go env GOHOSTOS)-$(go env GOHOSTARCH)
