#!/bin/bash

apt update
apt install -y upx-ucl

WORKDIR=$(pwd)
ln -s $WORKDIR $GOPATH/src/standardized
cd $GOPATH/src/standardized

env GOOS=linux GOARCH=arm go build -ldflags="-s -w" -v -o standardized-linux-arm . && upx -9 standardized-linux-arm
env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -v -o standardized-linux-arm64 . && upx -9 standardized-linux-arm64
env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -v -o standardized-linux-amd64 . && upx -9 standardized-linux-amd64
env GOOS=linux GOARCH=386 go build -ldflags="-s -w" -v -o standardized-linux-x86 . && upx -9 standardized-linux-x86
env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -v -o standardized-darwin-amd64 . && upx -9 standardized-darwin-amd64
